---
title: "War and State Development"
subtitle: "PSCI 2227, Spring 2026<br>Prof. Brenton Kenkel, Vanderbilt University"
---

## Reading Guides

| Date | Reading |
|------|---------|
| Wednesday, January 7 | [Spruyt 1994, 'Institutional Selection in International Relations: State Anarchy as Order'](guides/spruyt1994institutional.html) |
| Monday, January 12 | [Olson 1993, 'Dictatorship, Democracy, and Development'](guides/olson1993dictatorship.html) |
| Wednesday, January 14 | [Sánchez de la Sierra 2020, 'On the Origins of the State'](guides/sanchez2020origins.html) |
| Wednesday, January 21 | [Tilly 1990, 'How War Made States, and Vice Versa'](guides/tilly1990coercion.html) |
| Monday, January 26 | [Abramson 2017, 'The Economic Origins of the Territorial State'](guides/abramson2017economic.html) |
| Wednesday, February 4 | [Thies 2005, 'War, Rivalry, and State Building in Latin America'](guides/thies2005war.html) |
| Monday, February 9 | [Dincecco and Wang 2018, 'Violent Conflict and Political Development Over the Long Run: China versus Europe'](guides/dincecco2018violent.html) |
| Monday, February 16 | [Levi 1988, *Of Rule and Revenue*](guides/levi1988rule.html) |
| Wednesday, February 18 | [Karaman and Pamuk 2013, 'Different Paths to the Modern State in Europe'](guides/karaman2013different.html) |
| Monday, February 23 | [Queralt 2019, 'War, International Finance, and Fiscal Capacity in the Long Run'](guides/queralt2019war.html) |
| Wednesday, February 25 | [Kenkel and Paine 2023, 'A Theory of External Wars and European Parliaments'](guides/kenkel2023theory.html) |
| Wednesday, March 4 | [Cox, Dincecco, and Onorato 2023, 'Window of Opportunity: War and the Origins of Parliament'](guides/cox2023window.html) |
| Monday, March 16 | [Acemoglu and Robinson 2000, 'Why Did the West Extend the Franchise?'](guides/acemoglu2000did.html) |

: {tbl-colwidths="[35, 65]"}

## Lecture Slides

| Date | Topic |
|------|-------|
| Monday, January 5 | [Introduction to the course](slides/01-05_course_intro/01-05_course_intro.html){target="_blank"} |
| Wednesday, January 7 | [Sovereign states](slides/01-07_sovereign_states/01-07_sovereign_states.html){target="_blank"} |
| Monday, January 12 and Wednesday, January 14 | [Roving and stationary bandits](slides/01-12_roving_vs_stationary/01-12_roving_vs_stationary.html){target="_blank"} |
| Wednesday, January 21 | [How war made states in Europe](slides/01-21_war_made_states/01-21_war_made_states.html){target="_blank"} |
| Monday, February 2 | [European states: From war or wheat?](slides/02-02_war_or_wheat/02-02_war_or_wheat.html){target="_blank"} |
| Wednesday, February 4 | [War and statebuilding in Latin America](slides/02-04_latin_america/02-04_latin_america.html){target="_blank"} |
| Monday, February 9 | [Exit, voice, and war in Europe vs. China](slides/02-09_exit_voice/02-09_exit_voice.html){target="_blank"} |
| Monday, February 16 | [Raising revenue](slides/02-16_raising_revenue/02-16_raising_revenue.html){target="_blank"} |
| Wednesday, February 18 | [War and revenue: Statistical evidence](slides/02-18_revenue_evidence/02-18_revenue_evidence.html){target="_blank"} |
| Monday, February 23 | [Paying for war: Taxes versus debt](slides/02-23_taxes_vs_debt/02-23_taxes_vs_debt.html){target="_blank"} |
| Wednesday, February 25 | [How war affects elite incentives](slides/02-25_elite_incentives/02-25_elite_incentives.html){target="_blank"} |
| Wednesday, March 4 | [War, commerce, and the creation of parliaments](slides/03-04_parliamentary_creation/03-04_parliamentary_creation.html){target="_blank"} |

: {tbl-colwidths="[35, 65]"}
