---
title: "Anderson 1983, *Imagined Communities*"
date: 2026-03-25
---

## Notes

Popular writing often uses "nationalism" as a synonym for what I'd call "jingoism"---a sense not only of belonging to a national community, but that one's own national community is superior to others.
Anderson, like most scholars writing on the topic, uses "nationalism" to mean the identification of the political unit (the state) with a community of people (the nation).

## Questions

What are the "three paradoxes" of nationalism that Anderson identifies?
For each of the three: why does this paradox make it difficult to develop a coherent theory of nationalism?

What is Anderson's definition of nationalism?

- How does this definition contend with the three paradoxes?
- How is his concept more like "kinship" and "religion" than like "liberalism" or "fascism"?

Why does Anderson describe as absurd "a Tomb of the Unknown Marxist or a cenotaph for fallen Liberals."
And why is the analogous national Tomb of the Unknown Soldier *not* considered an absurdity?

What does nationalism offer that is similar to the "religious communities" and "dynastic realms" that preceded modern nationalism?
And in what ways does it differ from these predecessors?

What is the change in the sense of "time" that Anderson describes?
How does the modern "clock and calendar" sense of time enable nationalism to develop?

What is the role of printed language in the origins of nationalism?
How does the daily newspaper both signify and create a sense of national community?
