---
title: "Brewer 1988, *The Sinews of Power*, chapters 3--4"
date: 2026-04-13
---

## Questions

What were the major changes in British government service between the late 1600s and the middle 1700s?
Specifically, what were the broad patterns in:

- The number of people employed by the state?
- The extent of patronage and political loyalty necessary to acquire and retain an administrative position?
- The organization of public offices?
- The day-to-day nature of the work performed in these offices?

How were these changes connected to the extent of British involvement in warfare during the same time period?

When Britain lost the American Revolutionary War, what were the effects on movements to reform the civil service?
(To what extent do we---and don't we---see the classic Tilly argument playing out here?)

We have seen arguments that debt finance might act as a substitute for developing a proper system of domestic taxation.
Why does Brewer see debt and the tax system as being more like *complements* in the British case?

How did the changes in civil administration documented by Brewer in chapter 3 enable the increase in taxation he documents in chapter 4?

From a ruler's perspective, what are the pros and cons of direct tax collection compared to tax farming?

What is the Excise?
What does Brewer see as responsible for the growth in its importance as a revenue-raising mechanism for the British crown?

What were the most important differences between civil administration in Britain and in France/the Netherlands?
