---
title: "Sánchez de la Sierra 2020, 'On the Origins of the State'"
date: 2026-01-14
---

# Notes

From page 48 onward, this article contains a lot of math that I don't expect you to understand, especially if you haven't taken econometrics.
Keeping that in mind, here is how I would recommend approaching this article:

1.  Read pages 32--47 carefully.
    After summarizing the research question and findings (32--37), this will take you through the theory (37--40), the key questions/hypotheses (41--43), and an overview of the data that SdlS collected to test those hypotheses (43--47).
2.  Go back and [reread]{.underline} the summary of the main statistical findings on pages 34--35.  ("As a foundation for this study..." paragraph through "The third result is that..." paragraph.)
    This will give you the main need-to-know about the statistical analysis in the paper.
3.  Finally, give a *quick* skim to the full writeup of the statistical results on pages 48--70.
    Don't overinvest in trying to understand everything here, and definitely don't get bogged down in the mathematical parts.
    Just keep in mind the three main findings summarized on pages 34--35, and look for connections to the evidence that Sánchez de la Sierra presents here.

Read the really long footnotes if and only if you are personally interested in their content.
Almost by definition, a footnote cannot contain information that is critical to understand the central point of a paper.
Many of the long footnotes here are just Sánchez de la Sierra explaining to his audience of economists — who aren't typically trained in theories of state formation — the things you've already read in the Spruyt and Olson papers. 

::: {.callout-note title="Optional: How to read Table 1"}
In case you're interested in digging into the statistics a bit, but you haven't taken econometrics or a similar course, here's a brief guide to interpreting Table 1, which contains the paper's core statistical findings.

Each column in the table is a different dependent variable, measured across municipalities and years.
The dependent variable in column (1) is whether the municipality was attacked by an armed group in a given year.
Columns (2)--(6) give dependent variables measured for the mine(s) in a given municipality in a given year, and columns (7)--(9) give dependent variables measured for the support village.

The numbers in the first row, the one labeled $\text{Coltan}_j \times p_{ct}$, are estimates of the effect of an increase in the price of coltan on the given dependent variable, specifically in municipalities with a coltan mine.
A positive number represents a positive effect (increase) in the dependent variable, and a negative number represents a negative effect (decrease).
An set of asterisks, or "stars," appears by estimates that are [statistically significant](https://en.wikipedia.org/wiki/Statistical_significance) --- loosely speaking, where the pattern in the data is strong enough that we can rule out the idea that it's the sort of small variation that would arise in any random sample.

- For example, the entry in column (1), for municipality attacks, is `.15***` --- a positive, statistically significant effect.
  This means that when the price of coltan increases, coltan-producing municipalities are more likely to be attacked.
- Looking across at columns (2)--(6), containing mine site dependent variables, you'll see that every entry is positive, and most are statistically significant.
  This means that when the price of coltan increases, we see more indications of armed groups performing state-like functions at mining sites, including imposing customs taxes and providing security services.
- Meanwhile, in columns (7)--(9), containing support village dependent variables, the entries are all positive, but statistically insignificant.
  This means that the pattern in the data does reflect increased state-like behavior by armed groups in support villages for coltan-producing municipalities when the price of coltan increases, but not a strong enough pattern to separate this effect from the ordinary types of differences that would emerge in any sample of data.

The numbers in the second row, labeled $\text{Gold}_j \times p_{gt}$, are interpreted similarly to the numbers in the previous row.
The only difference is that these now represent estimated effects of an increase in the gold price on the corresponding dependent variable in gold-producing municipalities.
The overall story this row tells is that increases in gold prices have no discernible effect on armed groups' provision of state-like functions at mining sites in gold-producing municipalities, but they do have positive effects on the provision of state-like functions in support villages in those municipalities.
:::


# Questions

Why has it historically been challenging to find data to evaluate the theory that the state emerged as a "stationary bandit"?
According to Sánchez de la Sierra, why is the contemporary Democratic Republic of the Congo a setting where this theory can be studied?
The economic difference between coltan and gold is important in this article.
A key finding is that armed groups tax coltan-producing communities in the places where coltan itself is *produced*, whereas gold-producing communities are taxes in the places where earnings from gold production are *spent*.
According to Sánchez de la Sierra, what is the important difference in coltan versus gold production that explains this difference in the location of taxes?

Sánchez de la Sierra finds that Congolese households tend to be better off when there is a local militia or army acting as a stationary bandit nearby, but not when an armed group from outside the country controls the local economy.
How does this finding line up with Olson's theory of roving versus stationary bandits?

On pages 37--38, Sánchez de la Sierra describes how the NDC-R armed group interacts with more than a hundred villages under its control.
In what ways does this group meet — and fail to meet — Weber's definition of the state as an organization with a monopoly over the legitimate use of force in a given territory?

Sánchez de la Sierra observes that in the rural eastern portion of the country, each municipality consists of a single "support village" associated with one or more mining sites.
Why is this clear distinction between "mining sites" and "support villages" important for Sánchez de la Sierra to test his hypotheses about coltan versus gold as influences on the nature of governance by armed groups?

As you can see in Figure 3 (page 50), armed attacks on coltan-producing municipalities increased dramatically between 1999 and 2000, whereas attacks on gold-producing municipalities increased only slightly.
According to Sánchez de la Sierra, what is the primary explanation for this difference in attack patterns?
