---
title: "Spruyt 1994, 'Institutional Selection in International Relations: State Anarchy as Order'"
date: 2026-01-07
---

# Notes

We won't be concerned with the particulars of new institutional history (abbreviated to NIH through most of the article) and historical sociology.
Focus on the specific claims and evidence about the emergence, persistence, and extinction of different types of political organization in Europe.

- In practice, this means you can skip over the subsections "The deductive perspective of new institutionalism" and "Some problems with new institutionalism" on pages 530--533.
- The exception would be to read the paragraph that spans 531--532 if you need or want a refresher on free-riding and credible commitment.

When Spruyt refers to "the end of the feudal era," he's talking about the early 1300s.

# Questions

What does Spruyt mean when he says that the principle of sovereignty is that "authority is territorial and exclusive"?

Spruyt writes about four forms of political organization other than the sovereign state: feudalism, empire, city-leagues, and city-states.
(He also mentions theocracy, but does not cover it in enough detail to answer the following question.)
How does authority in each of these fail to be territorial and/or exclusive?

How does an empire handle trade?
What are the benefits and costs of the imperial approach for a merchant or trader operating within the empire?

What were the key differences between imperial and feudal approaches to trade?
Why was feudalism poorly equipped to handle the increase in trade and the rise of the merchant/burgher class?

Spruyt argues that standardization and hierarchy are key features of sovereign territorial states.
How did these features help a state's merchants engage in trade both within the state and outside its boundaries?

How did a city-league like the Hanseatic League differ from a sovereign state in terms of standardization and hierarchy?
What were the costs and benefits for ordinary traders?

How did the lack of clear territorial boundaries make it relatively difficult for the Hanseatic League to manage diplomatic relations with other political units?

How were city-states similar to, and different from, sovereign states and city-leagues in terms of standardization and hierarchy?
What were the consequences for the internal economy and external relations of city-states?

Spruyt claims that military competition is [not]{.underline} the main cause of why sovereign states outlasted competing forms of political organization.
What evidence does he present to support this conclusion?
